CREATE TABLE operadoras(
    DATA DATE NOT NULL,
    REG_ANS INT NOT NULL,
    CD_CONTA_CONTABIL BIGINT NOT NULL UNIQUE,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15, 2),
    VL_SALDO_FINAL DECIMAL(15, 2),
    INDEX idx_reg_ans (REG_ANS),
    INDEX idx_data (DATA)
);
